config/routes.rb
Omrails::Application.routes.draw do
  get "static_pages/tos"
  get "static_pages/privacy"
  resources :boards
 
  resources :pins

  get 'about' => "pages#about"
  
 root :to => 'pins#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :tests, :birthdays

  

end

app/models/board.rb
class Board < ActiveRecord::Base
  attr_accessible :description
belongs_to :user
  has_many :pins, through: :pinnings
accepts_nested_attributes_for :pins

  validates :user_id, presence: true
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.order("created_at desc").page(params[:page]).per_page(20)
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = current_user.boards.new
  end

  # GET /boards/1/edit
  def edit
    @board = current_user.boards.find(params[:id])
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = current_user.boards.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'board was successfully created.' }
        format.json { render action: 'show', status: :created, location: @board }
      else
        format.html { render action: 'new' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    @board = current_user.boards.find(params[:id])
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board = current_user.boards.find(params[:id])
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:description)
    end


def board_params
params.require(:board).permit(:description, :image, :image_remote_url)
end

end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board.html.erb
<div class="box">
  
    <p class="description">
        <%= board.description %>
    </p>
    <p>

    </p>
    <% if current_user == board.user %>
        <p>
          <%= link_to 'Edit', edit_board_path(board) %>
          <%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
    <% end %>
</div>

app/views/boards/_form.html.erb
<%= simple_form_for(@board, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :description, as: :text, input_html: { rows: "3" } %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<%= render 'pages/home' %>
<div id="boards">
  <%= render @boards %>
</div>
<%= will_paginate @boards %>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<div class="row">
    <div class="span6 offset3">
        <div class="well">
            <p>
              <%= @board.description %>
            </p>
            <%= link_to 'Edit', edit_board_path(@pin) %> |
            <%= link_to 'Back', boards_path %>
        </div>
    </div>
</div>