config/routes.rb
Omrails::Application.routes.draw do
  get "static_pages/tos"
  get "static_pages/privacy"
  resources :boards
 
  resources :pins

  get 'about' => "pages#about"
  
 root :to => 'pins#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :tests, :birthdays

  

end

app/views/layouts/_footer.html.erb
<div class="footer">
		<small>
			<%= link_to "Shopsavr", "http://www.shopsavr.com" %> </a> by 	<%= link_to "Me", "http://www.shopsavr.com" %>
		</small>
	</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
                          <%= link_to "Shopsavr", root_path, class: "brand" %>

                <div class="nav-collapse">
                    <ul class="nav">
                  
                        <li>
                            <%= link_to 'Home',  root_path %>
                        </li>
                        <li>    
                            <%= link_to 'About',  about_path %>
                        </li>
                    </ul>
                    <ul class="nav center">

                                           <%= form_tag pins_path, method: :get do %>
  <p>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", name: nil %>
  </p>
</ul>
<% end %>
                    <ul class="nav pull-right">

                        <% if user_signed_in? %>
                        <li><%= link_to 'Boards',  boards_path %></li>
                        <li><%= link_to 'Add +',  new_pin_path %></li>
                        <li><%= link_to 'Edit Profile',  edit_user_registration_path %></li>
                        <li><%= link_to 'Logout',  destroy_user_session_path, method: :delete %></li>
                        <% else %>
                                <li><%= link_to 'Login',  new_user_session_path %></li>
                                <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
                                
                                <% end %>
                    </ul>
                </div>
        </div>
    </div>
</div>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>One Month Rails</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	<%= render 'layouts/header' %>

<div class= 'container' %>
<% flash.each do |name, msg| %>
<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>
	<%= yield %>
	
	<%= render 'layouts/footer' %>
	<div>
	</body>
	</html>